# Generated by Django 4.1.5 on 2023-01-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
